name: Compilations

on: [push, pull_request]

# Github actions does not support YAML anchors.  This creative use of
# environment variables (plus the "echo ::set-env" hack) is to reroute that
# restriction.
env:
  default_cc: clang-11
  append_cc: ''
  crosshost: ''

  # -O1 is faster than -O3 in our tests... Majority of time are consumed trying
  # to optimize binaries.  Also Github Actions runs on a relatively modern CPU
  # compared to, say, GCC 4 or Clang 3.  We don't specify `-march=native`
  # because compilers tend not understand what the CPU is.
  optflags: '-O1'

  # -g0 disables backtraces when SEGV.  Do not set that.
  debugflags: '-ggdb3'

  default_configure: >-
    --enable-debug-env
    --disable-install-doc
    --with-ext=-test-/cxxanyargs,+
  append_configure: >-
    --without-valgrind
    --without-jemalloc
    --without-gmp

  UPDATE_UNICODE: >-
    UNICODE_FILES=.
    UNICODE_PROPERTY_FILES=.
    UNICODE_AUXILIARY_FILES=.
    UNICODE_EMOJI_FILES=.
  CONFIGURE_TTY: never
  GITPULLOPTIONS: --no-tags origin ${{github.ref}}
  RUBY_DEBUG: ci rgengc
  RUBY_TESTOPTS: >-
    -q
    --color=always
    --tty=no

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { key: default_cc, name: gcc-10,    value: gcc-10 }

    name: ${{ matrix.entry.name }}
    runs-on: [ds2v2]
    container: ghcr.io/ruby/ruby-ci-image:latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: mkdir build
        working-directory:
      - name: setenv
        run: |
          echo "${{ matrix.entry.key }}=${{ matrix.entry.value }}" >> $GITHUB_ENV
          echo "make=make -sj$((1 + $(nproc --all)))" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          path: src
      - run: autoconf
        working-directory: src
      - name: Run configure
        run: |
          if [ -n "${crosshost}" ]; then
            ../src/configure -C \
              ${default_configure} \
              ${append_configure} \
              --host="${crosshost}"
          else
            ../src/configure -C \
              ${default_configure} \
              ${append_configure} \
              --with-gcc="${default_cc} ${append_cc}"
          fi
      - run: $make extract-extlibs
      - run: $make incs
      - run: $make
      - run: $make test
      - run: $make install
        if: "matrix.entry.name == '-O3'"
      - run: /usr/local/bin/gem install --no-doc timezone tzinfo
        if: "matrix.entry.name == '-O3'"
      - run: $make test-tool
        if: "matrix.entry.name == '-O3'"
      - run: $make test-all TESTS='-- ruby -ext-'
        if: "matrix.entry.name == '-O3'"
      - run: $make test-spec
        if: "matrix.entry.name == '-O3'"

      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "ci": "GitHub Actions",
              "env": "${{ github.workflow }} / ${{ matrix.entry.name }}",
              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref }}".split('/').reverse()[0]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: failure() && github.event_name == 'push'

defaults:
  run:
    working-directory: build

